apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: save-images
  # namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/beemarie/saveimages
        env:
        - name: APIKEY
          value: Ade72jYlms7Zr5WUnSVr_WNv8OOft1be5R3g64SG2nTS
        - name: ENDPOINT
          value: s3.us-east.cloud-object-storage.appdomain.cloud
        - name: SERVICE_INSTANCE
          value: 'crn:v1:bluemix:public:cloud-object-storage:global:a/2da4019593524e2196c5919577116322:950042d3-bd67-474f-a5e9-3c94365d0f2c::'
        - name: BUCKET_NAME
          value: images-bmv
        - name: BUCKET_LOCATION
          value: us-east